package com.myspace.fsi_onboarding_test;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class checkListDoc implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String docName;

	public checkListDoc() {
	}

	public java.lang.String getDocName() {
		return this.docName;
	}

	public void setDocName(java.lang.String docName) {
		this.docName = docName;
	}

	public checkListDoc(java.lang.String docName) {
		this.docName = docName;
	}

}