package com.myspace.fsi_onboarding_test;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class QuestionnaireResponse implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.myspace.fsi_onboarding_test.QuestionAndAnswer> customerQuestionnaire;

	public QuestionnaireResponse() {
	}

	public java.util.List<com.myspace.fsi_onboarding_test.QuestionAndAnswer> getCustomerQuestionnaire() {
		return this.customerQuestionnaire;
	}

	public void setCustomerQuestionnaire(
			java.util.List<com.myspace.fsi_onboarding_test.QuestionAndAnswer> customerQuestionnaire) {
		this.customerQuestionnaire = customerQuestionnaire;
	}

	public QuestionnaireResponse(
			java.util.List<com.myspace.fsi_onboarding_test.QuestionAndAnswer> customerQuestionnaire) {
		this.customerQuestionnaire = customerQuestionnaire;
	}

}